# Generated by Django 6.0.1 on 2026-02-23 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='users.Follow', through_fields=('follower', 'following'), to=settings.AUTH_USER_MODEL),
        ),
    ]
