# Generated by Django 6.0.1 on 2026-02-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow_relationship',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
    ]
