# Generated by Django 6.0.1 on 2026-02-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_follow_users_follo_followe_3a2483_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
    ]
